# Generated by Django 5.0.4 on 2024-04-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_online_status',
            field=models.BooleanField(default=False),
        ),
    ]
